# Generated by Django 2.1 on 2018-08-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171227_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(auto_now_add=True)),
                ('clock_out', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='global_id',
            field=models.CharField(default='test', max_length=25),
            preserve_default=False,
        ),
    ]
