# Generated by Django 2.1 on 2018-08-20 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180820_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(default='8b2d97d9-06dd-48f8-812c-ba3e6398c556', on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
